/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V3RouteImport } from './routes/v3'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DeleteRouteImport } from './routes/delete'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiDeletionRequestRouteImport } from './routes/api/deletion-request'

const V3Route = V3RouteImport.update({
  id: '/v3',
  path: '/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteRoute = DeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeletionRequestRoute = ApiDeletionRequestRouteImport.update({
  id: '/api/deletion-request',
  path: '/api/deletion-request',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delete': typeof DeleteRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/v3': typeof V3Route
  '/api/deletion-request': typeof ApiDeletionRequestRoute
  '/api/waitlist': typeof ApiWaitlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delete': typeof DeleteRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/v3': typeof V3Route
  '/api/deletion-request': typeof ApiDeletionRequestRoute
  '/api/waitlist': typeof ApiWaitlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delete': typeof DeleteRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/v3': typeof V3Route
  '/api/deletion-request': typeof ApiDeletionRequestRoute
  '/api/waitlist': typeof ApiWaitlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delete'
    | '/privacy'
    | '/support'
    | '/v3'
    | '/api/deletion-request'
    | '/api/waitlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delete'
    | '/privacy'
    | '/support'
    | '/v3'
    | '/api/deletion-request'
    | '/api/waitlist'
  id:
    | '__root__'
    | '/'
    | '/delete'
    | '/privacy'
    | '/support'
    | '/v3'
    | '/api/deletion-request'
    | '/api/waitlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeleteRoute: typeof DeleteRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  V3Route: typeof V3Route
  ApiDeletionRequestRoute: typeof ApiDeletionRequestRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v3': {
      id: '/v3'
      path: '/v3'
      fullPath: '/v3'
      preLoaderRoute: typeof V3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete': {
      id: '/delete'
      path: '/delete'
      fullPath: '/delete'
      preLoaderRoute: typeof DeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deletion-request': {
      id: '/api/deletion-request'
      path: '/api/deletion-request'
      fullPath: '/api/deletion-request'
      preLoaderRoute: typeof ApiDeletionRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeleteRoute: DeleteRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  V3Route: V3Route,
  ApiDeletionRequestRoute: ApiDeletionRequestRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
